# This is a basic workflow that is manually triggered

name: Pull from upstream and generate an PR

on:
  push: 
    branches: [ master ]
  schedule:
    - cron: "* */6 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  generate-pr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2.3.2
      with:
        fetch-depth: '10'
        ref: 'master'
        token: ${{ secrets.GH_SERVICE_ACCOUNT_API_KEY }}
    
    - name: Add upstream to the remotes list
      run: git remote add upstream https://github.com/anuraghazra/github-readme-stats.git && git fetch --all
      
    - name: Add login info for service account
      run: git remote set-url origin https://RecapTimeBot:${GH_SERVICE_ACCOUNT_API_KEY}@github.com/MadeByThePinsHub/gh-readme-stats-vercel
    
    - name: Checkout the upstream repo as new branch
      run: git checkout -b "upstream/queued" "upstream/master"
    
    - name: Push it!
      run: git push origin upstream/queued
    
